#!/bin/bash -e

# import library functions
here_=`cd "$( dirname $(readlink -f "${BASH_SOURCE[0]}" ) )" && pwd`
. ${here_}/gwpysoftlib.sh

# update package
target=$1
package=$2
shift
pipargs=$@

. ${target}/bin/activate

echo -n "Updating `basename $package` ... "
install_package $package $target --upgrade
echo " done"

deactivate
